/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author lab026
 */
public class FontChange extends javax.swing.JDialog {

    /**
     * Creates new form Font
     *
     * @param parent
     * @param modal
     */
    public FontChange(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
    }

    public JLabel getLbPreview() {
        return lbPreview;
    }

    public void setLbPreview(JLabel lbPreview) {
        this.lbPreview = lbPreview;
    }

    

    public JButton getjButtonOk() {
        return jButtonOk;
    }

    public void setjButtonOk(JButton jButtonOk) {
        this.jButtonOk = jButtonOk;
    }

    public JList<String> getjListFamily() {
        return jListFamily;
    }

    public void setjListFamily(JList<String> jListFamily) {
        this.jListFamily = jListFamily;
    }

    public JList getjListSize() {
        return jListSize;
    }

    public void setjListSize(JList jListSize) {
        this.jListSize = jListSize;
    }

    public JList<String> getjListStyle() {
        return jListStyle;
    }

    public void setjListStyle(JList<String> jListStyle) {
        this.jListStyle = jListStyle;
    }

    public JTextField getjFontFamilyInput() {
        return jFontFamilyInput;
    }

    public void setjFontFamilyInput(JTextField jFontFamilyInput) {
        this.jFontFamilyInput = jFontFamilyInput;
    }

    public JTextField getjFontSizeInput() {
        return jFontSizeInput;
    }

    public void setjFontSizeInput(JTextField jFontSizeInput) {
        this.jFontSizeInput = jFontSizeInput;
    }

    public JTextField getjFontStyleInput() {
        return jFontStyleInput;
    }

    public void setjFontStyleInput(JTextField jFontStyleInput) {
        this.jFontStyleInput = jFontStyleInput;
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFont = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListFamily = new javax.swing.JList<>();
        jLabelFontStyle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListStyle = new javax.swing.JList<>();
        jLabelSize = new javax.swing.JLabel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jPanelSample = new javax.swing.JPanel();
        lbPreview = new javax.swing.JLabel();
        jScrollPaneSize = new javax.swing.JScrollPane();
        jListSize = new javax.swing.JList();
        jFontFamilyInput = new javax.swing.JTextField();
        jFontStyleInput = new javax.swing.JTextField();
        jFontSizeInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelFont.setDisplayedMnemonic('f');
        jLabelFont.setText("Font:");
        jLabelFont.setToolTipText("");

        jListFamily.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListFamilyValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListFamily);

        jLabelFontStyle.setDisplayedMnemonic('y');
        jLabelFontStyle.setText("Font Style:");

        jListStyle.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListStyleValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListStyle);

        jLabelSize.setDisplayedMnemonic('s');
        jLabelSize.setText("Size:");

        jButtonOk.setText("OK");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jPanelSample.setBorder(javax.swing.BorderFactory.createTitledBorder("Sample"));

        lbPreview.setText("AaBbYyZz");

        javax.swing.GroupLayout jPanelSampleLayout = new javax.swing.GroupLayout(jPanelSample);
        jPanelSample.setLayout(jPanelSampleLayout);
        jPanelSampleLayout.setHorizontalGroup(
            jPanelSampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSampleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPreview)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanelSampleLayout.setVerticalGroup(
            jPanelSampleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSampleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPreview)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jListSize.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSizeValueChanged(evt);
            }
        });
        jScrollPaneSize.setViewportView(jListSize);

        jFontFamilyInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFontFamilyInputActionPerformed(evt);
            }
        });

        jFontStyleInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFontStyleInputActionPerformed(evt);
            }
        });

        jFontSizeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFontSizeInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelSample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFontFamilyInput, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFont, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 9, Short.MAX_VALUE)
                                .addComponent(jLabelFontStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSize, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFontStyleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFontSizeInput)
                                    .addComponent(jScrollPaneSize, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFont)
                    .addComponent(jLabelFontStyle)
                    .addComponent(jLabelSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFontFamilyInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFontStyleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFontSizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPaneSize))
                .addGap(18, 18, 18)
                .addComponent(jPanelSample, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListFamilyValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListFamilyValueChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jListFamilyValueChanged

    private void jListStyleValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListStyleValueChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jListStyleValueChanged

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jListSizeValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSizeValueChanged
       
    }//GEN-LAST:event_jListSizeValueChanged

    private void jFontFamilyInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFontFamilyInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFontFamilyInputActionPerformed

    private void jFontStyleInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFontStyleInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFontStyleInputActionPerformed

    private void jFontSizeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFontSizeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFontSizeInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FontChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FontChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FontChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FontChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FontChange dialog = new FontChange(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JTextField jFontFamilyInput;
    private javax.swing.JTextField jFontSizeInput;
    private javax.swing.JTextField jFontStyleInput;
    private javax.swing.JLabel jLabelFont;
    private javax.swing.JLabel jLabelFontStyle;
    private javax.swing.JLabel jLabelSize;
    private javax.swing.JList<String> jListFamily;
    private javax.swing.JList jListSize;
    private javax.swing.JList<String> jListStyle;
    private javax.swing.JPanel jPanelSample;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPaneSize;
    private javax.swing.JLabel lbPreview;
    // End of variables declaration//GEN-END:variables
}
